services:
  grafana:
    image: k0rventen/apple-health-grafana-grafana:v0.5.0
    ports:
      - 3000:3000

  # VictoriaMetrics instance, a single process responsible for
  # storing metrics and serve read requests.
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.103.0
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - ./vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    restart: always

  ingester:
    image: k0rventen/apple-health-grafana-ingester:v0.5.0
    environment:
      - VICTORIAMETRICS_URL=http://victoriametrics:8428
    volumes:
      - <local_path_to_export.zip>:/export.zip
